spring:
  profiles:
    group:
      local: local, secret
      blue: blue, secret
      green: green, secret
server:
  env: blue

--- #local
spring:
  config:
    activate:
      on-profile: local
server:
  port: 8080
  serverAddress: localhost
serverName: local

--- #blue
spring:
  config:
    activate:
      on-profile: blue
server:
  port: 8080
  serverAddress: 43.202.133.109
serverName: blue-server

--- #green
spring:
  config:
    activate:
      on-profile: green
server:
  port: 8080
  serverAddress: 43.202.133.109
serverName: green-server